version: '3'

services:
  clean-api-ddd:
    image: bitnami/postgresql
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=clean-api-ddd
